### ISSUE TITLE
Question: Dynamic Topic Registration

### ISSUE THREAD

**Issue by bearrito** [ika-rwth-aachen/mqtt_client#25]
Hello,

Is there a technical reason, meaning in terms of MQTT operations, that topic registration could not be dynamic? 
I'm attempting to use the bridge for RVIZ. However, RVIZ topics can change based on what the team needs to visualize. Keeping the topic mapping file up to date could be a maintenance hassle.

**Comment by lreiher** [comment]
No, I don't see any technical reason. You can create new ROS subscriptions and broadcasters at any time, you can create new MQTT subscribers and broadcasters at any time. It's just that we have not yet seen a use case where one would like to change the mapped topics during runtime.

It should be totally possible though. One could imagine the node providing ROS services that can be called to set up a new ros2mqtt or mqtt2ros connection. For the former, one would need to fill a new struct in the `ros2mqtt_` container and create a new ROS subscriber [like here](https://github.com/ika-rwth-aachen/mqtt_client/blob/main/mqtt_client/src/MqttClient.cpp#L394). For the latter, one would need to fill a new struct in the `mqtt2ros_` container and create a new MQTT subscriber [like here](https://github.com/ika-rwth-aachen/mqtt_client/blob/main/mqtt_client/src/MqttClient.cpp#L806).

If you are interested in implementing this, feel free to fork the repository and later create a PR, would be happy to merge!

**Comment by bearrito** [comment]
@lreiher 

Yeah I've done this in the past with other queuing communications protocol. RosBridge does something as well. It does mean introducing a little bit more ROS machinery because you have to depend on rostopic package for looking up topics.  

I (my company) will likely end up forking and then contributing back.
