### ISSUE TITLE
Issues building with colcon

### ISSUE THREAD

**Issue by omer-arad** [ika-rwth-aachen/mqtt_client#27]
Hi,
I am trying to build this repository in a ROS2 Foxy Docker container, but I'm experiencing issues.
When I'm running:
`colcon build --packages-up-to mqtt_client --cmake-args -DCMAKE_BUILD_TYPE=Release`
I'm getting this following error:
```
Starting >>> mqtt_client_interfaces
Finished <<< mqtt_client_interfaces [5.14s]                     
Starting >>> mqtt_client
--- stderr: mqtt_client                             
/home/ws/src/mqtt_client/src/MqttClient.ros2.cpp:35:10: fatal error: rcpputils/env.hpp: No such file or directory
   35 | #include <rcpputils/env.hpp>
      |          ^~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/mqtt_client.dir/build.make:63: CMakeFiles/mqtt_client.dir/src/MqttClient.ros2.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:78: CMakeFiles/mqtt_client.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
---
Failed   <<< mqtt_client [3.89s, exited with code 2]

Summary: 1 package finished [9.43s]
  1 package failed: mqtt_client
  1 package had stderr output: mqtt_client
```

Any ideas what am I doing wrong? am I missing anything?

Thanks!

**Comment by lreiher** [comment]
Please see https://github.com/ika-rwth-aachen/mqtt_client/issues/19#issuecomment-1524746762.

Foxy is not officially supported and probably never will be, as it has just entered its end-of-life phase. Consider switching to the most recent long-term support ROS2 distribution called Humble.
