### ISSUE TITLE
 Unable to locate package ros-melodic-mqtt-client

### ISSUE THREAD

**Issue by hankge** [ika-rwth-aachen/mqtt_client#32]
Hi All, 
Thank you for your work on MQTT_Client! I do appreciate it.
I want to know if you guys have a suitable version for ubuntu18 or ubuntu20.
I tried it on ROS2, it works smoothly. But my code is runing in ROS-melodic.
Thank you in advanced.

**Comment by lreiher** [comment]
Please note that we do not officially support ROS Melodic, which has also gone into its end-of-life state in June 2023.

Theoretically it should be possible to build the `mqtt_client` under ROS Melodic yourself, but you will also have install dependencies such as `paho.mqtt.cpp` manually.

Consider upgrading to ROS Noetic or ROS 2.
