### ISSUE TITLE
I can'i search it form docker hub

### ISSUE THREAD

**Issue by is-whale** [ika-rwth-aachen/mqtt_client#40]
I need to run it on my Ubuntu 22.04，  I can't find it when I was used "docker search ghcr.io/ika-rwth-aachen/mqtt_client:ros"

**Comment by lreiher** [comment]
The Docker image is not published on DockerHub, but in GitHub's container registry, [see here](https://github.com/ika-rwth-aachen/mqtt_client/pkgs/container/mqtt_client). `docker search` only searches DockerHub.

If you run it like `docker run ghcr.io/ika-rwth-aachen/mqtt_client:ros`, it will automatically pull the image from the GitHub container registry.

**Comment by is-whale** [comment]
Thank you very much for your help!
