### ISSUE TITLE
ros2 foxy 版本如何安装？

### ISSUE THREAD

**Issue by hai411741962** [ika-rwth-aachen/mqtt_client#43]

**Comment by lreiher** [comment]
https://github.com/ika-rwth-aachen/mqtt_client/issues/27

**Comment by latale23** [comment]
i install humble on ubuntu 20 and clone it. but colcon build error 

![QQ图片20231225020208](https://github.com/ika-rwth-aachen/mqtt_client/assets/99425350/2310fe7f-1646-4882-98ef-a3d9c4de894c)

**Comment by lreiher** [comment]
```
rosdep install --ignore-src --from-paths src
```
