### ISSUE TITLE
Possible to know that previous message has been recieved by the client ?

### ISSUE THREAD

**Issue by prajwalthakur** [ika-rwth-aachen/mqtt_client#75]
I wanted to ask if it's possible to know whether a client has received the last message sent. Suppose machine-A is sending messages to machine-B. On machine-A, we have an MQTT broker as well. I know that with QoS 1 or 2, the receiving client sends an acknowledgment back to the broker. My question is whether it’s possible to broadcast this acknowledgment in a ROS server so that the publisher knows the last message has been received and can send new data.

I understand that one way is to generate a response message explicitly from machine-B and send it back to machine-A whenever new data is received, but I wanted to know if there’s another way to achieve this.

Thanks!

**Comment by lreiher** [comment]
There is currently no built-in way other than MQTT QoS levels for such a thing.
